version: '3'

services:
  retool-backend:
    image: tryretool/backend:3.44.8
    env_file: docker.env
    ports:
      - 3000:3000
    restart: always

  retool-frontend:
    image: tryretool/frontend:3.44.8
    env_file: docker.env
    ports:
      - 80:80
    restart: always

  postgres:
    image: postgres:16.8
    env_file: docker.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  
